function getFilteredProducts(){ const search=(document.getElementById('search-input')?.value || '').toLowerCase(); const category=document.querySelector('input[name="category"]:checked')?.value || 'all'; const price=document.getElementById('price-filter')?.value || 'all'; const rating=Number(document.getElementById('rating-filter')?.value || 0); const stock=document.getElementById('stock-filter')?.value || 'all'; const discount=document.getElementById('discount-filter')?.value || 'all'; const sort=document.getElementById('sort-filter')?.value || 'newest'; let products = PRODUCTS_DATA.filter((product)=>{ const matchesCategory = category === 'all' || product.category.toLowerCase() === category.toLowerCase(); const matchesSearch = !search || product.name.toLowerCase().includes(search) || product.category.toLowerCase().includes(search) || product.sku.toLowerCase().includes(search); const matchesPrice = price === 'all' || (price === 'under-5m' && product.price < 5000000) || (price === '5m-10m' && product.price >= 5000000 && product.price <= 10000000) || (price === 'above-10m' && product.price > 10000000); const matchesRating = !rating || product.rating >= rating; const matchesStock = stock === 'all' || (stock === 'instock' && product.stock > 0) || (stock === 'limited' && product.stock <= 8); const matchesDiscount = discount === 'all' || (discount === 'sale' && product.discount > 0); return matchesCategory && matchesSearch && matchesPrice && matchesRating && matchesStock && matchesDiscount; }); products = [...products].sort((a,b)=>{ switch(sort){ case 'oldest': return a.id.localeCompare(b.id); case 'lowest': return a.price - b.price; case 'highest': return b.price - a.price; case 'rating': return b.rating - a.rating; case 'az': return a.name.localeCompare(b.name); case 'za': return b.name.localeCompare(a.name); default: return b.price - a.price; }}); return products; }
function renderProductCatalog(containerId = 'catalog-grid'){ const container = document.getElementById(containerId); if(!container) return; const products = getFilteredProducts(); if(!products.length){ container.innerHTML = '<div class="panel" style="padding:2rem;grid-column:1/-1">Tidak ada produk yang cocok dengan filter saat ini.</div>'; return; } container.innerHTML = products.map((product)=>{ const discountedPrice = Math.round(product.price * (1 - product.discount/100)); const isWishlisted = store.wishlist.includes(product.id); return `
      <article class="product-card">
        <button class="wishlist-btn ${isWishlisted ? 'active' : ''}" onclick="toggleWishlist('${product.id}')">♡</button>
        <img class="product-image" src="${product.image}" alt="${product.name}">
        <div class="product-body">
          <span class="badge badge-${product.badge.toLowerCase().replace(/\s+/g, '')}">${product.badge}</span>
          <h3>${product.name}</h3>
          <p class="text-sm text-gray">${product.category} • SKU ${product.sku}</p>
          <div class="flex justify-between items-center text-sm"><span>⭐ ${product.rating}</span><span>${product.reviews} reviews</span></div>
          <div class="price-row"><div><div class="price">Rp ${discountedPrice.toLocaleString('id-ID')}</div><div class="strike">Rp ${product.price.toLocaleString('id-ID')}</div></div><span class="badge-pill">${product.stock} stok</span></div>
          <div class="flex gap-2 mt-2"><a href="product-detail.html?id=${product.id}" class="btn-outline" style="flex:1">Detail</a><button class="btn" style="flex:1" onclick="addToCart('${product.id}')">Add Cart</button></div>
        </div>
      </article>`; }).join(''); }
window.renderProductCatalog = renderProductCatalog; window.getFilteredProducts = getFilteredProducts;